/*
Project Euler - Problem #2:
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
#include <stdio.h>
int main(){
	int sum=0, t1=0, t2=1, t3=0, num=4000000;
	t3=t1+t2;
	while(t3<num){
    	t1=t2;
		t2=t3;
		t3=t1+t2;
		if(t3%2==0){
			sum+=t3;
		}
	}
	printf("Sum of even Fibonacci numbers up to %d: %d",num, sum);
	return 0;
}
